version: "3.8"
services:
  worker:
    build: .
    container_name: local_worker
    command: ["node", "worker.js"]
    depends_on:
      - webhook
    volumes:
      - ./data:/data
      - ./logs:/usr/src/app/logs
    env_file:
      - .env

  webhook:
    build: .
    container_name: local_webhook
    command: ["node", "webhook-server.js"]
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/usr/src/app/logs
    env_file:
      - .env
